Add clarification to set of non-normative deliverables
w3c/vc-wg-charter pull request #74
Opened 2022-02-15 21:16 UTC by brentzundel

This PR adds text to the non-normative deliverables section clarifying the status of listed items.
Thanks to @jricher for the opening line.

Signed-off-by: Brent Zundel <brent.zundel@gmail.com>

2022-02-16 02:27 UTC, kdenhartog requested changes
It's implied that the reason for doing this is that it's so that we have the ability to create notes as we choose when the WG is happening. However, I believe this is a misguided approach to the purpose of Notes and is actually regressive in terms of patent protection according to the [W3C process document Notes section](https://www.w3.org/2021/Process-20211102/#note-track). Most notably Notes are "not intended to be a formal standard" which is not true from my understanding of many of these documents and Notes are not patent protected. I think we either need to actually make many of these documents REC track documents or we need to leave them as CCG reports so that they at least remain protected by the [community group patent policy](https://www.w3.org/community/about/process/summary/).

2022-02-16 04:10 UTC, Sakurann approved these changes

2022-02-16 05:29 UTC, iherman approved these changes

2022-02-16 05:40 UTC, iherman commented
@kdenhartog,

>[…] I believe this is a misguided approach to the purpose of Notes and is actually regressive in terms of patent protection according to the [W3C process document Notes section](https://www.w3.org/2021/Process-20211102/#note-track). Most notably Notes are "not intended to be a formal standard" which is not true from my understanding of many of these documents and Notes are not patent protected. 

You are right for individual notes re patent issues. However... this is not, in my view, a discussion to have here and now. Instead, for each document the WG will have to make a decision whether it intends to work on a specific  subject, and that decision will have to take into account the potential patent aspect, too. It is not up to the charter to make this decision, nor can it do it in abstract. As the proposed text says, this list is non-exhaustive, nor is it a _requirement_ to publish these notes. (in fact, if this PR is acceptable, we may think of reducing the list).

> I think we either need to actually make many of these documents REC track documents or we need to leave them as CCG reports so that they at least remain protected by the [community group patent policy](https://www.w3.org/community/about/process/summary/).

What we cannot do easily, during the WG's life, is to decide whether a document would become REC track. Any such decision would require a re-chartering of the group. _That_ decision is to be made now. Whether a document should be a CCG spec instead of a Note is then something the WG will have to decide, weighting the pros and cons of the choice.

2022-02-16 18:38 UTC, selfissued approved these changes

2022-02-16 20:50 UTC, msporny approved these changes

2022-02-16 20:50 UTC, dlongley approved these changes

2022-02-16 20:51 UTC, kdenhartog approved these changes
In the case of what @iherman has said and the discussion on the call today, I believe this is fine.

2022-02-16 20:52 UTC, Sakurann commented on index.html
> +Group will use its discretion to decide which, if any, to work on, and may publish WG Notes or other documents not
probably paraphrase
> Group will use its discretion to decide which, if any, to work on the documents not listed here.

2022-02-17 02:21 UTC, Sakurann commented on index.html
> +non-exhaustive selection of documents the Working Group may wish to produce as WG Notes or other documents. The Working
```suggestion
non-exhaustive selection of documents the Working Group may wish to produce. The Working
```

2022-02-17 02:22 UTC, Sakurann commented on index.html
> +Group will use its discretion to decide which, if any, to work on, and may publish WG Notes or other documents not
made a suggestion in a line above per a comment during VCWG call on 2022-Feb-16th.

2022-02-17 06:04 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-02-16-vcwg#section4-2) on 2022-02-16

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.2. Add clarification to description of non-normative deliverables (pr vc-wg-charter#74)

_See github pull request [vc-wg-charter#74](https://github.com/w3c/vc-wg-charter/pull/74)._




**Brent Zundel:** pull title is Add clarification to description of non-normative deliverables #74.  
… summary is that we'll work on what ever time, attention, and resources permit.  
… we have comments.  
… we have approvals.  
… we have concerns.  
… any opposition to merge?.  

**Kyle Den Hartog:** unrequesting changes and now approve..  

**Kristina Yasuda:** suggested some text. approved..  

**Brent Zundel:** can merge with your suggestion as a comment..  

</details>

2022-02-23 16:16 UTC, mkhraisha approved these changes

2022-02-23 16:19 UTC, merged

2022-02-23 17:14 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-02-23-vcwg#section4-2) on 2022-02-23

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.2. Add clarification to description of non-normative deliverables (pr vc-wg-charter#74)

_See github pull request [vc-wg-charter#74](https://github.com/w3c/vc-wg-charter/pull/74)._




**Manu Sporny:** kristina you asked for some changes, do you want you changes applied before we merge?.  

> *Orie Steele:* confusion over PRs....

**Michael Jones:** we need to merge 74.  

**Manu Sporny:** we are talking about 74.  

**Michael Jones:** merge 74.  

**Brent Zundel:** did you add kristina's comment?.  

**Manu Sporny:** yes.  

**Brent Zundel:** objection to mergeng 74?.  
… no objections, merging 74..  

</details>