Clarify IETF liaison
w3c/vc-wg-charter pull request #80
Opened 2022-02-23 18:29 UTC by brentzundel

fixes #52 
Signed-off-by: Brent Zundel <brent.zundel@gmail.com>

***
<a href="https://pr-preview.s3.amazonaws.com/brentzundel/vc-wg-charter/pull/80.html" title="Last updated on Mar 1, 2022, 9:29 PM UTC (3273ea9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-wg-charter/80/6ad9969...brentzundel:3273ea9.html" title="Last updated on Mar 1, 2022, 9:29 PM UTC (3273ea9)">Diff</a>

2022-02-24 01:36 UTC, kdenhartog approved these changes

2022-02-25 03:15 UTC, msporny commented on index.html
> +                <dt><a href="https://datatracker.ietf.org/group/secdir/about/">Internet Engineering Task Force Security Area Advisory Group</a> </dt>
The removed \<dd> is important. The SAAG won't do broad horizontal reviews, will it @samuelweiler? The reason the SAD was in there before was to tell us "Oh, you want X... then you need to talk with Y." Will the SAAG do that for us now (I'm not familiar w/ them)?

I guess the question is -- who is going to tell us "If you want that sort of review, you need to go /over there/."?

2022-03-01 20:55 UTC, selfissued requested changes
To my knowledge, neither the IESG nor SAAG have formal liaison relationships, so it doesn't make sense to include them here.  Please remove them.

That said, when we think we're ready, I'm great with informally asking either or both if they'd be willing to do a friendly review, possibly assisted by Mark Nottingham, who had expressed interest in helping in the past.

2022-03-01 20:59 UTC, msporny commented
@mnot, what would be the best way to say "We would like to work with the Security People at IETF when it comes to reviewing the normative output for this W3C Working Group?".

This is what's in the charter right now under the Liasons section:

[Internet Engineering Task Force Security Area Directorate](https://datatracker.ietf.org/group/secdir/about/)
To coordinate broad horizontal reviews on the output of the Working Group among the security working groups at IETF.
[Internet Engineering Task Force Crypto Forum Research Group](https://datatracker.ietf.org/rg/cfrg/about/)
To perform broad horizontal reviews on the output of the Working Group and to ensure that new pairing-based and post-quantum cryptographic algorithms and parameters can be integrated into the Data Integrity ecosystem.

@samuelweiler wanted us to replace the SAD with the SAAG. @selfissued is saying don't list the liaison relationship at all. 

Help, please.

2022-03-01 21:06 UTC, mnot commented
Perhaps it's best to say something a bit more fuzzy, like:

Internet Engineering Task Force
The Working Group will seek security review from the IETF, coordinated through the Liaison

2022-03-01 21:29 UTC, brentzundel commented
@selfissued @msporny @samuelweiler 
I have revised the PR according to the suggestions from @mnot, please review

2022-03-01 21:57 UTC, selfissued approved these changes
Fine now - thanks

2022-03-01 22:33 UTC, msporny approved these changes
I'm fine w/ being less precise.

2022-03-01 22:57 UTC, Sakurann approved these changes

2022-03-02 05:32 UTC, iherman commented
@samuelweiler, this PR (and the linked issue) is an answer to your comment; are you o.k. with this, so that we can merge this PR and close the corresponding issue?

2022-03-02 15:52 UTC, merged

2022-03-02 15:52 UTC, brentzundel commented
Merging this PR in accordance with our current working mode. If further changes are desired, we can track those in the related issue #52